import { BrainCircuit, Check, Minus, Sparkles } from 'lucide-react';
import { useSuggestTags } from '../hooks/useSuggestTags';
import { useApplyTag } from '../hooks/useApplyTag';
import { confidenceLevels } from '../types/tag';
import { cn } from '../utils/cn';

const confidenceCopy: Record<(typeof confidenceLevels)[number], { label: string; tone: string }> = {
  low: { label: 'Low', tone: 'bg-slate-700 text-slate-200' },
  medium: { label: 'Medium', tone: 'bg-amber-500/20 text-amber-200' },
  high: { label: 'High', tone: 'bg-emerald-500/20 text-emerald-200' }
};

export const TagSuggestions = () => {
  const { note, suggestions } = useSuggestTags();
  const { apply, remove } = useApplyTag();

  if (!note) {
    return (
      <div className="space-y-4">
        <h2 className="flex items-center gap-2 text-lg font-semibold text-white">
          <BrainCircuit className="h-5 w-5 text-sky-300" aria-hidden />
          Smart suggestions
        </h2>
        <p className="text-sm text-slate-400">
          Select a note to receive AI-assisted tagging recommendations.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="flex items-center gap-2 text-lg font-semibold text-white">
          <BrainCircuit className="h-5 w-5 text-sky-300" aria-hidden />
          Suggested tags
        </h2>
        <span className="text-xs uppercase tracking-widest text-slate-500">
          {note.title}
        </span>
      </div>
      {suggestions.length === 0 ? (
        <div className="rounded-lg border border-dashed border-white/10 bg-slate-900/40 p-4 text-sm text-slate-400">
          No suggestions available. Try adding more descriptive content.
        </div>
      ) : (
        <ul className="space-y-3">
          {suggestions.map((item) => (
            <li
              key={item.tag.id}
              className="rounded-lg border border-white/5 bg-slate-950/70 p-4 shadow-inner shadow-black/20"
            >
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div className="flex items-center gap-3">
                  <span
                    aria-hidden
                    className="h-3 w-3 rounded-full"
                    style={{ backgroundColor: item.tag.color }}
                  />
                  <div>
                    <p className="text-sm font-semibold text-white">{item.tag.name}</p>
                    <p className="text-xs text-slate-400">{item.reason}</p>
                  </div>
                </div>
                <span
                  className={cn(
                    'rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-wide',
                    confidenceCopy[item.confidence].tone
                  )}
                >
                  {confidenceCopy[item.confidence].label} confidence
                </span>
              </div>
              {item.keywords.length > 0 && (
                <p className="mt-2 text-xs text-slate-400">
                  Keywords: <span className="text-slate-100">{item.keywords.join(', ')}</span>
                </p>
              )}
              <div className="mt-3 flex flex-wrap items-center gap-2">
                <button
                  onClick={() => apply(item.tag.id, 'ai', true)}
                  className="inline-flex items-center gap-2 rounded-lg bg-emerald-500/20 px-3 py-1.5 text-xs font-semibold text-emerald-100 transition hover:bg-emerald-500/30 focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400"
                >
                  <Check className="h-3.5 w-3.5" aria-hidden />
                  Accept tag
                </button>
                <button
                  onClick={() => remove(item.tag.id)}
                  className="inline-flex items-center gap-2 rounded-lg bg-rose-500/20 px-3 py-1.5 text-xs font-semibold text-rose-100 transition hover:bg-rose-500/30 focus:outline-none focus-visible:ring-2 focus-visible:ring-rose-400"
                >
                  <Minus className="h-3.5 w-3.5" aria-hidden />
                  Reject
                </button>
              </div>
            </li>
          ))}
        </ul>
      )}
      <div className="rounded-lg border border-sky-500/20 bg-sky-500/10 p-4 text-xs text-sky-100">
        <div className="mb-2 flex items-center gap-2 font-semibold">
          <Sparkles className="h-4 w-4" aria-hidden />
          How it works
        </div>
        <p>
          Suggestions are generated by analysing keywords, intent and your feedback loop. Accepting or rejecting tags trains the
          model for higher accuracy.
        </p>
      </div>
    </div>
  );
};
